### PR TITLE
Namechanges

### PR DESCRIPTION
**Pull request by cdwensley**
This PR replaces PreCat1ByTailHeadEmbedding by PreCat1Obj and IsGeneral2dMapping by IsGeneral2DimensionalMapping, so as to agree with the usage in XMod. 
The second commit changes xmod.tst to agree with the latest printing (with GAP 4.9.0). 

I see that the xymatrix diagram in the Cat1Algebra chapter of the manual is not working. 
The only way I know to fix this is to convert the manual to use AutoDoc (I've already done this with all the Bangor packages).  So I will have a go at that next - it will have to be in the same PR since the same files will be affected. 

The third commit makes a change in examples/cat1.g.  I decided a while ago, for the Bangor packages, that the example files were unnecessary since they only duplicated the material in the tests.  (Where there was additional material, I have moved it to xtst/*.tst and these files can be run using xtst/testextra.g.). So I suggest you "git rm" the files in examples/ and also examples/ itself.

### CODE REVIEW

**Comment by cdwensley** [comment]
The fourth commit uses AutoDoc to make the manual. 
The file doc/manual.xml is no longer needed - relevant bits are moved to PackageInfo.g and makedoc.g.  makedoc,g now QUITs when it finishes, which is the standard procedure. 
Files XModAlg.xml and title.xml are created automatically whenever makedoc.g is run. 

However: Travis tests appear to fail with the same sort of problem that I thought I had fixed with the second commit.  Is it possible that the algebra generators can vary from one run to another?  If so, then there are bound to be diffs with the tests as they stand at present.  In that case is it possible to change the data being printed to something more reliable? 

Apart from that this PR is ready to be considered for acceptance.

**Comment by fingolfin** [comment]
The test diffs are strange -- I just tried this PR on my computer, and the tests pass just fine. But I have a slightly different set of packages than what is used by Travis; so perhaps the version of some dependency of xmodalg is different between Travis on the one hand, and Chris' and my system on the other hand, and this is then causing the difference, indirectly?

**Comment by cdwensley** [comment]
ViewObj for XModAlgebras X1, X2 in xmod.tst Prints their Source and Range using ```gap> PrintApplicableMethod(PrintObj,[Source(X1)]);
this method is contained in lines [2023,2030] of file:
    /Applications/gap/gapdev/lib/algebra.gi
function ( A )
    if IsEmpty( GeneratorsOfAlgebra( A ) ) then
        Print( "Algebra( ", LeftActingDomain( A ), ", [], ", Zero( A ), " )" 
         );
    else
        Print( "Algebra( ", LeftActingDomain( A ), ", ", 
         GeneratorsOfAlgebra( A ), " )" );
    fi;
    return;
end
``` so it seems to be GeneratorsOfAlgebra which returns a different set on Travis?

**Comment by cdwensley** [comment]
... so it seems that it is GeneratorsOfAlgebra which returns different answers on Travis?

**Comment by cdwensley** [comment]
Tweaked Display for XModAlgebras at alg2obj.gi, line 530, using ViewObj in place of PrintObj. 
This results in changes of the outputs in xmod.tst and cat1.tst.  Maybe Travis tests will now pass? 
Took the opportunity to fix some of the indentation.

**Comment by cdwensley** [comment]
Made the same temporary change for Displaying morphisms of XModAlgebras in alg2map.gi. 
Commented out the printing of theta at xmod.tst line 167.

**Comment by cdwensley** [comment]
But Travis tests still fail, so tweak some more ...

**Comment by cdwensley** [comment]
Travis tests now pass since xmod.tst and cat1.tst no longer print lists of generators of algebras. 
The original print statements in these tests have been left in the manual examples.

**Comment by cdwensley** [comment]
Testing the printing of algebra generators without loading XModAlg shows that the change is introduced when the Semigroups package is loaded.  I will raise an issue somewhere tomorrow.

**Comment by cdwensley** [comment]
Further investigation reveals that Semigroups (version 3.0.14) is not available on Travis; so the change in algebra generators resulting from Semigroups does not occur; and a diff is reported.

**Comment by olexandr-konovalov** [comment]
@cdwensley note that it's not available because xmodalg travis scripts do not even attempt to build it. You need to update them.

**Comment by cdwensley** [comment]
Changing the travis scripts to force the loading of Semigroups results in the tests failing because Semigroups fails to build.  Since tests pass after this PR has been merged, it seems best to now leave well alone.  One day, when Semigroups does compile on Travis, we can think about reverting the changes to xmod.tst and cat1.tst.  I will raise an issue to this effect.

**Pull request merged**
