### PR TITLE
Set up Travis CI and CodeCov

### PR DESCRIPTION
**Pull request by cdwensley**
This PR adds files .codecov.yml, .travis.yml, folder scripts/, and four *.sh files in this folder. 
These files are used centrally for testing commits to a package (see: https://travis-ci.org/gap-packages/) and Alexander has requested me create this PR.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
Interesting, how did it happen that .codecov.yml and .travis.yml have identical content? They are different. So, because of the wrong .travis.yml the build fails.

**Comment by cdwensley** [comment]
No idea how that happened, but the problem has affected all 6 packages. 
Am fixing it now.

**Comment by cdwensley** [comment]
This should be the correct file, .travis.yml.

**Comment by olexandr-konovalov** [comment]
@cdwensley wonderful - tests are passing. You may click on "Show all checks" above to see details. You now can add badges as I explained elsewhere too, and that will be the end of a crash-course "how to configure Travis CI and CodeCov for a GAP package" 🥇

**Pull request merged**
