### PR TITLE
now AlgebraHomomorphismByFunction2 avoiding conflict with FR

### PR DESCRIPTION
**Pull request by cdwensley**
Alex K. has reported XModAlg segfaulting with AllPackagesLoaded. 
Possibly this is due to AlgebraHomomorphismByFunction being defined in different ways in FR and XModAlg.  This temporary fix renames the XModAlg version AlgebraHomomorphismByFunction2.

### CODE REVIEW

**Comment by cdwensley** [comment]
In the longer term it appears that AlgebraHomomorphismByFunction is of general interest and would be better moved to Utils - will contact Laurent about this.

**Comment by olexandr-konovalov** [comment]
I am afraid this will mask some problem that was introduced in the core GAP system yesterday. There was no new FR release, and all tests worked a day before. Perhaps you've now report the problem at https://github.com/gap-system/gap/issues/2401 ?

**Comment by cdwensley** [comment]
So this PR should NOT be merged (at present). 
No idea what the codecov/patch check failure is.

**Comment by olexandr-konovalov** [comment]
@cdwensley codecov complains that the coverage of the changed code is lower (25%) then the overall code coverage of the package code (43.51%). It's for package maintainer to decide whether to ignore this for now or add more tests.

**Comment by cdwensley** [comment]
Whatever the problem was, it was not the fault of XModAlg, so closing this PR.

**Pull request closed without merging**
